// <auto-generated />
using System;
using CoreComponents;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

namespace CoreComponents.Migrations
{
    [DbContext(typeof(PraxisContext))]
    [Migration("20210121181128_serverbounds")]
    partial class serverbounds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CoreComponents.DbTables+AreaControlTeam", b =>
                {
                    b.Property<long>("AreaControlTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGeneratedArea")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("MapDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("claimedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("points")
                        .HasColumnType("bigint");

                    b.HasKey("AreaControlTeamId");

                    b.HasIndex("FactionId");

                    b.HasIndex("MapDataId");

                    b.ToTable("AreaControlTeams");
                });

            modelBuilder.Entity("CoreComponents.DbTables+AreaType", b =>
                {
                    b.Property<int>("AreaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AreaName")
                        .HasColumnType("longtext");

                    b.Property<string>("HtmlColorCode")
                        .HasColumnType("longtext");

                    b.Property<string>("OsmTags")
                        .HasColumnType("longtext");

                    b.HasKey("AreaTypeId");

                    b.ToTable("AreaTypes");
                });

            modelBuilder.Entity("CoreComponents.DbTables+ErrorLog", b =>
                {
                    b.Property<int>("ErrorLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.HasKey("ErrorLogId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("CoreComponents.DbTables+Faction", b =>
                {
                    b.Property<long>("FactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("HtmlColor")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("FactionId");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("CoreComponents.DbTables+GeneratedMapData", b =>
                {
                    b.Property<long>("GeneratedMapDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<Geometry>("place")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("type")
                        .HasColumnType("longtext");

                    b.HasKey("GeneratedMapDataId");

                    b.ToTable("GeneratedMapData");
                });

            modelBuilder.Entity("CoreComponents.DbTables+MapData", b =>
                {
                    b.Property<long>("MapDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RelationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WayId")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<Geometry>("place")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("type")
                        .HasColumnType("longtext");

                    b.HasKey("MapDataId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("WayId");

                    b.ToTable("MapData");
                });

            modelBuilder.Entity("CoreComponents.DbTables+MapTile", b =>
                {
                    b.Property<long>("MapTileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpireOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PlusCode")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("mode")
                        .HasColumnType("int");

                    b.Property<int>("resolutionScale")
                        .HasColumnType("int");

                    b.Property<byte[]>("tileData")
                        .HasColumnType("longblob");

                    b.HasKey("MapTileId");

                    b.HasIndex("PlusCode");

                    b.ToTable("MapTiles");
                });

            modelBuilder.Entity("CoreComponents.DbTables+PerformanceInfo", b =>
                {
                    b.Property<int>("PerformanceInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("calledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("functionName")
                        .HasColumnType("longtext");

                    b.Property<string>("notes")
                        .HasColumnType("longtext");

                    b.Property<long>("runTime")
                        .HasColumnType("bigint");

                    b.HasKey("PerformanceInfoID");

                    b.ToTable("PerformanceInfo");
                });

            modelBuilder.Entity("CoreComponents.DbTables+PlayerData", b =>
                {
                    b.Property<int>("PlayerDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("deviceID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("PlayerDataID");

                    b.HasIndex("deviceID");

                    b.ToTable("PlayerData");
                });

            modelBuilder.Entity("CoreComponents.DbTables+PremadeResults", b =>
                {
                    b.Property<long>("PremadeResultsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<string>("PlusCode6")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("PremadeResultsId");

                    b.HasIndex("PlusCode6");

                    b.ToTable("PremadeResults");
                });

            modelBuilder.Entity("CoreComponents.DbTables+ServerSetting", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("EastBound")
                        .HasColumnType("double");

                    b.Property<double>("NorthBound")
                        .HasColumnType("double");

                    b.Property<double>("SouthBound")
                        .HasColumnType("double");

                    b.Property<double>("WestBound")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("CoreComponents.DbTables+TurfWarConfig", b =>
                {
                    b.Property<int>("TurfWarConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cell10LockoutTimer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Repeating")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TurfWarDurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("TurfWarNextReset")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TurfWarConfigId");

                    b.ToTable("TurfWarConfigs");
                });

            modelBuilder.Entity("CoreComponents.DbTables+PaintTownEntry", b =>
                {
                    b.Property<long>("TurfWarEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CanFlipFactionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cell10")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cell8")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("TurfWarConfigId")
                        .HasColumnType("int");

                    b.HasKey("TurfWarEntryId");

                    b.HasIndex("Cell10");

                    b.HasIndex("Cell8");

                    b.HasIndex("FactionId");

                    b.HasIndex("TurfWarConfigId");

                    b.ToTable("TurfWarEntries");
                });

            modelBuilder.Entity("CoreComponents.DbTables+TurfWarScoreRecord", b =>
                {
                    b.Property<long>("TurfWarScoreRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Results")
                        .HasColumnType("longtext");

                    b.Property<int>("TurfWarConfigId")
                        .HasColumnType("int");

                    b.Property<int>("WinningFactionID")
                        .HasColumnType("int");

                    b.Property<int>("WinningScore")
                        .HasColumnType("int");

                    b.HasKey("TurfWarScoreRecordId");

                    b.HasIndex("TurfWarConfigId");

                    b.HasIndex("WinningFactionID");

                    b.ToTable("TurfWarScoreRecords");
                });

            modelBuilder.Entity("CoreComponents.DbTables+TurfWarTeamAssignment", b =>
                {
                    b.Property<long>("TurfWarTeamAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("TurfWarConfigId")
                        .HasColumnType("int");

                    b.Property<string>("deviceID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("TurfWarTeamAssignmentId");

                    b.HasIndex("FactionId");

                    b.HasIndex("TurfWarConfigId");

                    b.HasIndex("deviceID");

                    b.ToTable("TurfWarTeamAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
