// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OsmXmlParser.Database;

namespace OsmXmlParser.Migrations
{
    [DbContext(typeof(OsmParserContext))]
    partial class OsmParserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OsmXmlParser.Database.AreaType", b =>
                {
                    b.Property<int>("AreaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsmTags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaTypeId");

                    b.ToTable("AreaTypes");
                });

            modelBuilder.Entity("OsmXmlParser.Database.InterestingPoint", b =>
                {
                    b.Property<long>("InterestingPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("OsmWayId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlusCode2")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("PlusCode8")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<long>("ProcessedWayID")
                        .HasColumnType("bigint");

                    b.Property<string>("areaType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestingPointId");

                    b.HasIndex("PlusCode8");

                    b.ToTable("InterestingPoints");
                });

            modelBuilder.Entity("OsmXmlParser.Database.ProcessedWay", b =>
                {
                    b.Property<long>("ProcessedWayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<long>("OsmWayId")
                        .HasColumnType("bigint");

                    b.Property<double>("distanceE")
                        .HasColumnType("float");

                    b.Property<double>("distanceN")
                        .HasColumnType("float");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("latitudeS")
                        .HasColumnType("float");

                    b.Property<double>("longitudeW")
                        .HasColumnType("float");

                    b.HasKey("ProcessedWayId");

                    b.HasIndex("OsmWayId");

                    b.ToTable("ProcessedWays");
                });
#pragma warning restore 612, 618
        }
    }
}
